### ISSUE TITLE
Readme Upgrade - CDN Install Instructions

### ISSUE THREAD

**Issue by PandelisZ** [d4software/tweetthisjs#3]
I think the readme could use a bit of love.

One idea I had is to include the `<script>` from the CDN and just say, use this + the prerequisites and profit.

Copy pasting the src code is also always an option but this makes the readme sleeker.

I'd put it up on github.com/cdnjs/cdnjs but to do this we'd need a package manager for this to keep track of version. So publish to npm would be required, or a package.json at the very least. (publish is  a bonus I guess)

Alternative to this would just be a https://rawgit.com/ link but I don't know, that seems _raw_

I'll make a PR with this in shortly but I wanted to ask for your approval before submitting to cdnjs

**Comment by wgx** [comment]
Yeah go for it - cdnjs sounds like the way to go. 👍
